name: pokemon
description: "An assessment from Jarvix"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State management library for Flutter. Used for managing app state and dependencies easily.
  get: ^4.6.6

  # Lightweight storage solution. Used for local data storage, such as caching small amounts of user data.
  get_storage: ^2.1.1

  # Internationalization package. Used for handling localization and formatting dates, numbers, and currencies.
  intl: ^0.19.0

  # A powerful HTTP client library. Used for making network requests and handling APIs.
  dio: ^5.6.0

  # Interceptor for Dio. Used to log, retry, and handle requests or responses more easily.
  awesome_dio_interceptor: ^1.2.0

  # Checks for active internet connection. Used to validate connectivity before making network requests.
  internet_connection_checker_plus: ^2.5.2

  # Utility for responsive UI. Used for scaling UI elements based on screen size and device resolution.
  flutter_screenutil: ^5.9.3

  # Google Fonts library. Used for easily accessing and applying custom fonts from Google Fonts.
  google_fonts: ^6.2.1

  # Image caching library. Used to efficiently load and cache images from the network to reduce loading times and save bandwidth.
  cached_network_image: ^3.4.0

  # Annotation library for JSON serialization. Used for marking model classes to generate fromJson and toJson methods.
  json_annotation: ^4.9.0

  # Shimmer effect library. Used to display loading placeholders with a shimmering animation while content is being loaded.
  shimmer: ^3.0.0

  # SVG rendering library. Used to display scalable vector graphics (SVG) images in Flutter applications.
  flutter_svg: ^2.0.10+1

  # Animation library. Used to add ready-made, customizable animations like fade, bounce, and slide to widgets.
  animate_do: ^3.3.4

  # Focus detection library. Used to detect when a widget gains or loses focus, helpful for resource management and visibility tracking.
  focus_detector_v2: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  # To ease the setup of flavors for the projects
  flutter_flavorizr: ^2.2.3

flavorizr:
  flavors:
    development:
      app:
        name: "Pokémon Development"
      android:
        applicationId: "com.issacandco.pokemon.development"
      ios:
        bundleId: "com.issacandco.pokemon.development"

    staging:
      app:
        name: "Pokémon Staging"
      android:
        applicationId: "com.issacandco.pokemon.staging"
      ios:
        bundleId: "com.issacandco.pokemon.staging"

    production:
      app:
        name: "Pokémon"
      android:
        applicationId: "com.issacandco.pokemon"
      #        firebase:
      #          config: 'firebase/production/google-services.json'
      ios:
        bundleId: "com.issacandco.pokemon"
#        firebase:
#          config: 'firebase/production/GoogleService-Info.plist'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
